server:
  port: 8989

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: ticket-service
          uri: lb://ticket-service
          predicates:
            - Path=/api/tickets/**
        - id: payment-service
          uri: lb://payment-service
          predicates:
             - Path=/api/payment/**


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
